- app/src/main/kotlin/com/simplemobiletools/contacts/overloads/String.kt
Has better performance than StringBuffer
> Use StringBuilder in String.times()

- app/src/main/res/values-de/strings.xml
Latest translation for multiple commits.
> Update German DE

- app/src/main/kotlin/com/simplemobiletools/contacts/helpers/ContactsHelper.kt
https://github.com/SimpleMobileTools/Simple-Contacts/issues/31
> fix #31, lowering the number of bulk update lists

- app/src/main/res/layout/item_add_favorite_without_number.xml
This option exists in 'item_add_favorite_with_number.xml' file but not in 'item_add_favorite_without_number.xml' file.
> Added missing clickable option to checkbox

- app/src/main/res/values-lt/strings.xml
> Updated Lithuanian translation

- app/src/main/kotlin/com/simplemobiletools/contacts/helpers/VcfExporter.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/helpers/VcfImporter.kt
```
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:;Test User
TEL;TYPE=cell:125478963
TEL;TYPE=cell:66666
CATEGORIES:Testgroup,Testgroup1
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 2;Test
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 1;Test
CATEGORIES:Testgroup1
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 3;Test
CATEGORIES:Testgroup1
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 4;Test
END:VCARD
```
> Solution to Issue #146

- app/src/debug/res/values-eu/strings.xml
- app/src/main/res/values-eu/strings.xml
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)
> Updated eu (Basque) translation

- app/src/main/res/values-id/strings.xml
- app/src/main/res/values-in/strings.xml
Add another Indonesian translation file, "**in**". And some minor translation changes.
> Indonesian translation update

- app/src/main/res/values-de/strings.xml
I shortened the description further to achieve 77 characters.
> Updated short description

- app/src/main/res/values-es/strings.xml
To translate the app to Spanish
> Create string.xml Español

- app/src/main/res/values-zh-rCN/strings.xml
> Updated zh_CN strings.xml

- app/src/main/res/values-de/strings.xml
Translate show_private_contacts
> Update strings.xml, item show_private_contacts

- app/src/main/res/values-zh-rCN/strings.xml
> Small fixes for zh_CN translation.

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/GroupContactsActivity.kt
- app/src/main/res/menu/menu_group.xml
Hi
I've tried adding an implementation of RingtonePicker to assign a custom ringtone across a Group.
> Add option to set ringtone for Groups

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/dialogs/ChangeSortingDialog.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/ContactsHelper.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/models/Contact.kt
- app/src/main/res/layout/dialog_change_sorting.xml
Addresses #71.
Refactored `compareTo` function in `Contact` class for it to be clear after adding another comparison type.
> Allow sorting contacts by date created

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/ViewContactActivity.kt
- app/src/main/res/layout/activity_view_contact.xml
Addresses #625.
I just reverted commit a996a40, and the old full picture view seems to be working. @tibbi Is this sufficient?
> Add back ability to view full contact picture

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/fragments/MyViewPagerFragment.kt
> Don't show letters with diacritics in the scrollbar

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfExporter.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfImporter.kt
Addresses #697.
- Export partial dates to vCard 3.0 with the year 1900.
- Adjust import to use `partialDate` from v4.0 if there is no `date` field.
> Export partial dates to vCard 3.0 with year 1900

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/MainActivity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/adapters/ContactsAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/dialogs/ChangeSortingDialog.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/fragments/MyViewPagerFragment.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/Config.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/Constants.kt
- app/src/main/res/layout/dialog_change_sorting.xml
> Allow reordering favorites by drag and drop

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/adapters/FilterContactSourcesAdapter.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/dialogs/ExportContactsDialog.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/dialogs/FilterContactSourcesDialog.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/models/ContactSource.kt
> Show contact count at contact sources

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/ContactActivity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/EditContactActivity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/extensions/Activity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/ContactsHelper.kt
- app/src/main/res/layout/item_edit_phone_number.xml
> Set default phone number for contact

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/EditContactActivity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/ViewContactActivity.kt
- app/src/main/res/layout/item_view_phone_number.xml
- Added the default number indicator at the view details
- For duplicated contacts, try to reuse default number
- Update the default number in all contact sources
> Add the default number indicator at the View Details too

- app/build.gradle
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/ContactActivity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/extensions/Context.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfExporter.kt
Closes https://github.com/SimpleMobileTools/Simple-Contacts/issues/803
> Export formatted name as well as structured name 

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfExporter.kt
Hello,
This PR fixes #925.
Co-authored-by: @Pachat2000
> Fix phone category

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfExporter.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfImporter.kt
Hello,
This PR fixes #952 
Co-authored-by: @Pachat2000
> Use PREF for the preference rather than the number type

- app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/ViewContactActivity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/extensions/Activity.kt
- app/src/main/kotlin/com/simplemobiletools/contacts/pro/helpers/VcfExporter.kt
Reducing the vcf file version to be able to share contacts via WhatsApp. Fixed #942
> Contacts sharing fix
